# This file was auto-generated by Fern from our API Definition.

import typing

InitiatePhoneCallCallsResponseDataStatus = typing.Union[
    typing.Literal["initiated", "connecting", "active", "completed", "failed"], typing.Any
]
