# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing_extensions
import typing
from ...core.serialization import FieldMetadata
from .initiate_phone_call_calls_response_data_status import InitiatePhoneCallCallsResponseDataStatus
import datetime as dt
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class InitiatePhoneCallCallsResponseData(UniversalBaseModel):
    call_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="callId")] = None
    room_name: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="roomName")] = None
    conversation_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="conversationId")] = None
    status: typing.Optional[InitiatePhoneCallCallsResponseDataStatus] = None
    livekit_url: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="livekitUrl")] = None
    created_at: typing_extensions.Annotated[typing.Optional[dt.datetime], FieldMetadata(alias="createdAt")] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
