# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing_extensions
import typing
from ...core.serialization import FieldMetadata
import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class InitiateWebCallCallsRequestMetadata(UniversalBaseModel):
    """
    Optional metadata for the call
    """

    assistant_name: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="assistantName")] = (
        pydantic.Field(default=None)
    )
    """
    Custom name for the assistant
    """

    system_prompt: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="systemPrompt")] = (
        pydantic.Field(default=None)
    )
    """
    Custom system prompt
    """

    start_message: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="startMessage")] = (
        pydantic.Field(default=None)
    )
    """
    Initial message from the agent
    """

    background_sound: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="backgroundSound")] = (
        pydantic.Field(default=None)
    )
    """
    Background sound URL
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
