# This file was auto-generated by Fern from our API Definition.

import typing

ListCallsRequestStatus = typing.Union[
    typing.Literal["queued", "ringing", "in-progress", "completed", "failed", "busy", "no-answer"], typing.Any
]
