# This file was auto-generated by Fern from our API Definition.

import typing
from ..core.client_wrapper import SyncClientWrapper
from ..core.request_options import RequestOptions
from json.decoder import JSONDecodeError
from ..core.api_error import ApiError
from ..types.create_agent_transcriber import CreateAgentTranscriber
from ..types.create_agent_model import CreateAgentModel
from ..types.create_agent_voice import CreateAgentVoice
from ..types.agent_response import AgentResponse
from ..core.serialization import convert_and_respect_annotation_metadata
from ..core.pydantic_utilities import parse_obj_as
from ..errors.bad_request_error import BadRequestError
from ..errors.unauthorized_error import UnauthorizedError
from ..core.jsonable_encoder import jsonable_encoder
from ..errors.not_found_error import NotFoundError
from ..core.client_wrapper import AsyncClientWrapper

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AgentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(
        self, *, limit: typing.Optional[int] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Retrieve a paginated list of all AI voice agents configured for the authenticated organization.

        Parameters
        ----------
        limit : typing.Optional[int]
            Maximum number of agents to return per page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from ortavox import OrtaVox

        client = OrtaVox(
            api_key="YOUR_API_KEY",
            token="YOUR_TOKEN",
        )
        client.agents.list()
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/agents",
            method="GET",
            params={
                "limit": limit,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def create(
        self,
        *,
        name: str,
        transcriber: CreateAgentTranscriber,
        model: CreateAgentModel,
        voice: CreateAgentVoice,
        max_call_duration: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AgentResponse:
        """
        Create a new AI agent with specified configuration. Requires authentication via Clerk JWT or API key.

        Parameters
        ----------
        name : str
            Agent name

        transcriber : CreateAgentTranscriber

        model : CreateAgentModel

        voice : CreateAgentVoice

        max_call_duration : typing.Optional[float]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentResponse
            Agent created successfully

        Examples
        --------
        from ortavox import (
            CreateAgentModel,
            CreateAgentTranscriber,
            CreateAgentVoice,
            OrtaVox,
        )

        client = OrtaVox(
            api_key="YOUR_API_KEY",
            token="YOUR_TOKEN",
        )
        client.agents.create(
            name="Support Agent",
            transcriber=CreateAgentTranscriber(
                provider="deepgram",
                model="nova-3",
                language="en",
            ),
            model=CreateAgentModel(
                provider="openai",
                model="gpt-4o-mini",
                system_prompt="You are a helpful AI assistant",
                temperature=1.1,
                max_tokens=1.1,
            ),
            voice=CreateAgentVoice(
                provider="elevenlabs",
                voice_id="dqzVFKHwZvR9YMQoFM67",
                model="eleven_turbo_v2_5",
            ),
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/agents",
            method="POST",
            json={
                "name": name,
                "transcriber": convert_and_respect_annotation_metadata(
                    object_=transcriber, annotation=CreateAgentTranscriber, direction="write"
                ),
                "model": convert_and_respect_annotation_metadata(
                    object_=model, annotation=CreateAgentModel, direction="write"
                ),
                "voice": convert_and_respect_annotation_metadata(
                    object_=voice, annotation=CreateAgentVoice, direction="write"
                ),
                "max_call_duration": max_call_duration,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    AgentResponse,
                    parse_obj_as(
                        type_=AgentResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def get(self, agent_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Retrieve a specific agent

        Parameters
        ----------
        agent_id : str
            Agent ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from ortavox import OrtaVox

        client = OrtaVox(
            api_key="YOUR_API_KEY",
            token="YOUR_TOKEN",
        )
        client.agents.get(
            agent_id="agentId",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/agents/{jsonable_encoder(agent_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def delete(self, agent_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Delete an agent by ID

        Parameters
        ----------
        agent_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from ortavox import OrtaVox

        client = OrtaVox(
            api_key="YOUR_API_KEY",
            token="YOUR_TOKEN",
        )
        client.agents.delete(
            agent_id="agentId",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/agents/{jsonable_encoder(agent_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def update(
        self,
        agent_id: str,
        *,
        name: str,
        transcriber: CreateAgentTranscriber,
        model: CreateAgentModel,
        voice: CreateAgentVoice,
        max_call_duration: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Partially update agent configuration. Only provided fields will be updated.

        Parameters
        ----------
        agent_id : str
            Agent ID

        name : str
            Agent name

        transcriber : CreateAgentTranscriber

        model : CreateAgentModel

        voice : CreateAgentVoice

        max_call_duration : typing.Optional[float]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from ortavox import (
            CreateAgentModel,
            CreateAgentTranscriber,
            CreateAgentVoice,
            OrtaVox,
        )

        client = OrtaVox(
            api_key="YOUR_API_KEY",
            token="YOUR_TOKEN",
        )
        client.agents.update(
            agent_id="agentId",
            name="Support Agent",
            transcriber=CreateAgentTranscriber(
                provider="deepgram",
                model="nova-3",
                language="en",
            ),
            model=CreateAgentModel(
                provider="openai",
                model="gpt-4o-mini",
                system_prompt="You are a helpful AI assistant",
                temperature=1.1,
                max_tokens=1.1,
            ),
            voice=CreateAgentVoice(
                provider="elevenlabs",
                voice_id="dqzVFKHwZvR9YMQoFM67",
                model="eleven_turbo_v2_5",
            ),
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/agents/{jsonable_encoder(agent_id)}",
            method="PATCH",
            json={
                "name": name,
                "transcriber": convert_and_respect_annotation_metadata(
                    object_=transcriber, annotation=CreateAgentTranscriber, direction="write"
                ),
                "model": convert_and_respect_annotation_metadata(
                    object_=model, annotation=CreateAgentModel, direction="write"
                ),
                "voice": convert_and_respect_annotation_metadata(
                    object_=voice, annotation=CreateAgentVoice, direction="write"
                ),
                "max_call_duration": max_call_duration,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncAgentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self, *, limit: typing.Optional[int] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Retrieve a paginated list of all AI voice agents configured for the authenticated organization.

        Parameters
        ----------
        limit : typing.Optional[int]
            Maximum number of agents to return per page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from ortavox import AsyncOrtaVox

        client = AsyncOrtaVox(
            api_key="YOUR_API_KEY",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agents.list()


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/agents",
            method="GET",
            params={
                "limit": limit,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def create(
        self,
        *,
        name: str,
        transcriber: CreateAgentTranscriber,
        model: CreateAgentModel,
        voice: CreateAgentVoice,
        max_call_duration: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AgentResponse:
        """
        Create a new AI agent with specified configuration. Requires authentication via Clerk JWT or API key.

        Parameters
        ----------
        name : str
            Agent name

        transcriber : CreateAgentTranscriber

        model : CreateAgentModel

        voice : CreateAgentVoice

        max_call_duration : typing.Optional[float]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentResponse
            Agent created successfully

        Examples
        --------
        import asyncio

        from ortavox import (
            AsyncOrtaVox,
            CreateAgentModel,
            CreateAgentTranscriber,
            CreateAgentVoice,
        )

        client = AsyncOrtaVox(
            api_key="YOUR_API_KEY",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agents.create(
                name="Support Agent",
                transcriber=CreateAgentTranscriber(
                    provider="deepgram",
                    model="nova-3",
                    language="en",
                ),
                model=CreateAgentModel(
                    provider="openai",
                    model="gpt-4o-mini",
                    system_prompt="You are a helpful AI assistant",
                    temperature=1.1,
                    max_tokens=1.1,
                ),
                voice=CreateAgentVoice(
                    provider="elevenlabs",
                    voice_id="dqzVFKHwZvR9YMQoFM67",
                    model="eleven_turbo_v2_5",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/agents",
            method="POST",
            json={
                "name": name,
                "transcriber": convert_and_respect_annotation_metadata(
                    object_=transcriber, annotation=CreateAgentTranscriber, direction="write"
                ),
                "model": convert_and_respect_annotation_metadata(
                    object_=model, annotation=CreateAgentModel, direction="write"
                ),
                "voice": convert_and_respect_annotation_metadata(
                    object_=voice, annotation=CreateAgentVoice, direction="write"
                ),
                "max_call_duration": max_call_duration,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    AgentResponse,
                    parse_obj_as(
                        type_=AgentResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def get(self, agent_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Retrieve a specific agent

        Parameters
        ----------
        agent_id : str
            Agent ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from ortavox import AsyncOrtaVox

        client = AsyncOrtaVox(
            api_key="YOUR_API_KEY",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agents.get(
                agent_id="agentId",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/agents/{jsonable_encoder(agent_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def delete(self, agent_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Delete an agent by ID

        Parameters
        ----------
        agent_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from ortavox import AsyncOrtaVox

        client = AsyncOrtaVox(
            api_key="YOUR_API_KEY",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agents.delete(
                agent_id="agentId",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/agents/{jsonable_encoder(agent_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def update(
        self,
        agent_id: str,
        *,
        name: str,
        transcriber: CreateAgentTranscriber,
        model: CreateAgentModel,
        voice: CreateAgentVoice,
        max_call_duration: typing.Optional[float] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Partially update agent configuration. Only provided fields will be updated.

        Parameters
        ----------
        agent_id : str
            Agent ID

        name : str
            Agent name

        transcriber : CreateAgentTranscriber

        model : CreateAgentModel

        voice : CreateAgentVoice

        max_call_duration : typing.Optional[float]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from ortavox import (
            AsyncOrtaVox,
            CreateAgentModel,
            CreateAgentTranscriber,
            CreateAgentVoice,
        )

        client = AsyncOrtaVox(
            api_key="YOUR_API_KEY",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agents.update(
                agent_id="agentId",
                name="Support Agent",
                transcriber=CreateAgentTranscriber(
                    provider="deepgram",
                    model="nova-3",
                    language="en",
                ),
                model=CreateAgentModel(
                    provider="openai",
                    model="gpt-4o-mini",
                    system_prompt="You are a helpful AI assistant",
                    temperature=1.1,
                    max_tokens=1.1,
                ),
                voice=CreateAgentVoice(
                    provider="elevenlabs",
                    voice_id="dqzVFKHwZvR9YMQoFM67",
                    model="eleven_turbo_v2_5",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/agents/{jsonable_encoder(agent_id)}",
            method="PATCH",
            json={
                "name": name,
                "transcriber": convert_and_respect_annotation_metadata(
                    object_=transcriber, annotation=CreateAgentTranscriber, direction="write"
                ),
                "model": convert_and_respect_annotation_metadata(
                    object_=model, annotation=CreateAgentModel, direction="write"
                ),
                "voice": convert_and_respect_annotation_metadata(
                    object_=voice, annotation=CreateAgentVoice, direction="write"
                ),
                "max_call_duration": max_call_duration,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
