# This file was auto-generated by Fern from our API Definition.

import typing
from ..core.client_wrapper import SyncClientWrapper
from .types.initiate_web_call_calls_request_metadata import InitiateWebCallCallsRequestMetadata
from ..core.request_options import RequestOptions
from .types.initiate_web_call_calls_response import InitiateWebCallCallsResponse
from ..core.serialization import convert_and_respect_annotation_metadata
from ..core.pydantic_utilities import parse_obj_as
from ..errors.unauthorized_error import UnauthorizedError
from ..errors.not_found_error import NotFoundError
from json.decoder import JSONDecodeError
from ..core.api_error import ApiError
from .types.initiate_phone_call_calls_response import InitiatePhoneCallCallsResponse
from ..errors.bad_request_error import BadRequestError
from .types.list_calls_request_status import ListCallsRequestStatus
from ..core.jsonable_encoder import jsonable_encoder
from ..core.client_wrapper import AsyncClientWrapper

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class CallsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def initiate_web_call(
        self,
        *,
        agent_id: str,
        metadata: typing.Optional[InitiateWebCallCallsRequestMetadata] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> InitiateWebCallCallsResponse:
        """
        Start a web-based voice call with an AI agent

        Parameters
        ----------
        agent_id : str
            UUID of the agent to use for the call

        metadata : typing.Optional[InitiateWebCallCallsRequestMetadata]
            Optional metadata for the call

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InitiateWebCallCallsResponse
            Web call initiated successfully

        Examples
        --------
        from ortavox import OrtaVox

        client = OrtaVox(
            api_key="YOUR_API_KEY",
            token="YOUR_TOKEN",
        )
        client.calls.initiate_web_call(
            agent_id="agent_id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/calls/web-call",
            method="POST",
            json={
                "agent_id": agent_id,
                "metadata": convert_and_respect_annotation_metadata(
                    object_=metadata, annotation=InitiateWebCallCallsRequestMetadata, direction="write"
                ),
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    InitiateWebCallCallsResponse,
                    parse_obj_as(
                        type_=InitiateWebCallCallsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def initiate_phone_call(
        self,
        *,
        from_number: str,
        to_number: str,
        agent_id: str,
        dynamic_variables: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> InitiatePhoneCallCallsResponse:
        """
        Start an outbound phone call with an AI agent

        Parameters
        ----------
        from_number : str
            Phone number to call from (E.164 format) - must be a registered phone number

        to_number : str
            Phone number to call to (E.164 format)

        agent_id : str
            ID of the agent to use for the call

        dynamic_variables : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]
            Optional dynamic variables to pass to the agent (key-value pairs)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InitiatePhoneCallCallsResponse
            Phone call initiated successfully

        Examples
        --------
        from ortavox import OrtaVox

        client = OrtaVox(
            api_key="YOUR_API_KEY",
            token="YOUR_TOKEN",
        )
        client.calls.initiate_phone_call(
            from_number="+448450950002",
            to_number="+14157774444",
            agent_id="123e4567-e89b-12d3-a456-426614174000",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/calls/phone-call",
            method="POST",
            json={
                "from_number": from_number,
                "to_number": to_number,
                "agent_id": agent_id,
                "dynamic_variables": dynamic_variables,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    InitiatePhoneCallCallsResponse,
                    parse_obj_as(
                        type_=InitiatePhoneCallCallsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def list(
        self,
        *,
        status: typing.Optional[ListCallsRequestStatus] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Get all calls for the authenticated user

        Parameters
        ----------
        status : typing.Optional[ListCallsRequestStatus]
            Filter calls by their specific lifecycle status. Useful for polling active calls.

        limit : typing.Optional[int]
            Maximum number of calls to return for pagination purposes.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from ortavox import OrtaVox

        client = OrtaVox(
            api_key="YOUR_API_KEY",
            token="YOUR_TOKEN",
        )
        client.calls.list()
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/calls",
            method="GET",
            params={
                "status": status,
                "limit": limit,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def get(self, call_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Retrieve detailed information about a specific call

        Parameters
        ----------
        call_id : str
            Call ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from ortavox import OrtaVox

        client = OrtaVox(
            api_key="YOUR_API_KEY",
            token="YOUR_TOKEN",
        )
        client.calls.get(
            call_id="callId",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/calls/{jsonable_encoder(call_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncCallsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def initiate_web_call(
        self,
        *,
        agent_id: str,
        metadata: typing.Optional[InitiateWebCallCallsRequestMetadata] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> InitiateWebCallCallsResponse:
        """
        Start a web-based voice call with an AI agent

        Parameters
        ----------
        agent_id : str
            UUID of the agent to use for the call

        metadata : typing.Optional[InitiateWebCallCallsRequestMetadata]
            Optional metadata for the call

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InitiateWebCallCallsResponse
            Web call initiated successfully

        Examples
        --------
        import asyncio

        from ortavox import AsyncOrtaVox

        client = AsyncOrtaVox(
            api_key="YOUR_API_KEY",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.calls.initiate_web_call(
                agent_id="agent_id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/calls/web-call",
            method="POST",
            json={
                "agent_id": agent_id,
                "metadata": convert_and_respect_annotation_metadata(
                    object_=metadata, annotation=InitiateWebCallCallsRequestMetadata, direction="write"
                ),
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    InitiateWebCallCallsResponse,
                    parse_obj_as(
                        type_=InitiateWebCallCallsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def initiate_phone_call(
        self,
        *,
        from_number: str,
        to_number: str,
        agent_id: str,
        dynamic_variables: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> InitiatePhoneCallCallsResponse:
        """
        Start an outbound phone call with an AI agent

        Parameters
        ----------
        from_number : str
            Phone number to call from (E.164 format) - must be a registered phone number

        to_number : str
            Phone number to call to (E.164 format)

        agent_id : str
            ID of the agent to use for the call

        dynamic_variables : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]
            Optional dynamic variables to pass to the agent (key-value pairs)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InitiatePhoneCallCallsResponse
            Phone call initiated successfully

        Examples
        --------
        import asyncio

        from ortavox import AsyncOrtaVox

        client = AsyncOrtaVox(
            api_key="YOUR_API_KEY",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.calls.initiate_phone_call(
                from_number="+448450950002",
                to_number="+14157774444",
                agent_id="123e4567-e89b-12d3-a456-426614174000",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/calls/phone-call",
            method="POST",
            json={
                "from_number": from_number,
                "to_number": to_number,
                "agent_id": agent_id,
                "dynamic_variables": dynamic_variables,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    InitiatePhoneCallCallsResponse,
                    parse_obj_as(
                        type_=InitiatePhoneCallCallsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def list(
        self,
        *,
        status: typing.Optional[ListCallsRequestStatus] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Get all calls for the authenticated user

        Parameters
        ----------
        status : typing.Optional[ListCallsRequestStatus]
            Filter calls by their specific lifecycle status. Useful for polling active calls.

        limit : typing.Optional[int]
            Maximum number of calls to return for pagination purposes.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from ortavox import AsyncOrtaVox

        client = AsyncOrtaVox(
            api_key="YOUR_API_KEY",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.calls.list()


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/calls",
            method="GET",
            params={
                "status": status,
                "limit": limit,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def get(self, call_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Retrieve detailed information about a specific call

        Parameters
        ----------
        call_id : str
            Call ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from ortavox import AsyncOrtaVox

        client = AsyncOrtaVox(
            api_key="YOUR_API_KEY",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.calls.get(
                call_id="callId",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/calls/{jsonable_encoder(call_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
