# This file was auto-generated by Fern from our API Definition.

import typing

ImportNumberTelephonyResponseDataAuthState = typing.Union[
    typing.Literal["authenticated", "not_authenticated", "server_error", "not_verified"], typing.Any
]
