# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing
from .import_number_telephony_response_data_auth_state import ImportNumberTelephonyResponseDataAuthState
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class ImportNumberTelephonyResponseData(UniversalBaseModel):
    phone_number: typing.Optional[str] = None
    inbound_sip_trunk_id: typing.Optional[str] = None
    outbound_sip_trunk_id: typing.Optional[str] = None
    auth_state: typing.Optional[ImportNumberTelephonyResponseDataAuthState] = None
    auth_state_message: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
