# This file was auto-generated by Fern from our API Definition.

import typing
from ..core.client_wrapper import SyncClientWrapper
from .types.import_number_telephony_request_direction import ImportNumberTelephonyRequestDirection
from ..core.request_options import RequestOptions
from .types.import_number_telephony_response import ImportNumberTelephonyResponse
from ..core.pydantic_utilities import parse_obj_as
from ..errors.unauthorized_error import UnauthorizedError
from ..errors.conflict_error import ConflictError
from json.decoder import JSONDecodeError
from ..core.api_error import ApiError
from ..core.jsonable_encoder import jsonable_encoder
from ..errors.not_found_error import NotFoundError
from ..core.client_wrapper import AsyncClientWrapper

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class TelephonyClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def import_number(
        self,
        *,
        phone_number: str,
        termination_uri: str,
        direction: typing.Optional[ImportNumberTelephonyRequestDirection] = OMIT,
        sip_auth_username: typing.Optional[str] = OMIT,
        sip_auth_password: typing.Optional[str] = OMIT,
        inbound_agent_id: typing.Optional[str] = OMIT,
        outbound_agent_id: typing.Optional[str] = OMIT,
        inbound_agent_version: typing.Optional[int] = OMIT,
        outbound_agent_version: typing.Optional[int] = OMIT,
        nickname: typing.Optional[str] = OMIT,
        inbound_webhook_url: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ImportNumberTelephonyResponse:
        """
        Import a phone number from custom telephony and bind agents

        Parameters
        ----------
        phone_number : str
            E.164 format phone number

        termination_uri : str
            SIP trunk termination URI

        direction : typing.Optional[ImportNumberTelephonyRequestDirection]
            Which direction(s) to configure - inbound only, outbound only, or both. Defaults to both if not specified.

        sip_auth_username : typing.Optional[str]
            SIP authentication username (required)

        sip_auth_password : typing.Optional[str]
            SIP authentication password (required)

        inbound_agent_id : typing.Optional[str]
            Agent ID for inbound calls

        outbound_agent_id : typing.Optional[str]
            Agent ID for outbound calls

        inbound_agent_version : typing.Optional[int]
            Inbound agent version

        outbound_agent_version : typing.Optional[int]
            Outbound agent version

        nickname : typing.Optional[str]
            Friendly name for the phone number

        inbound_webhook_url : typing.Optional[str]
            Webhook URL for inbound call events

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ImportNumberTelephonyResponse
            Phone number imported successfully

        Examples
        --------
        from ortavox import OrtaVox

        client = OrtaVox(
            api_key="YOUR_API_KEY",
            token="YOUR_TOKEN",
        )
        client.telephony.import_number(
            phone_number="+14157774444",
            termination_uri="sip.uk.didlogic.net",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/telephony/import",
            method="POST",
            json={
                "phone_number": phone_number,
                "termination_uri": termination_uri,
                "direction": direction,
                "sip_auth_username": sip_auth_username,
                "sip_auth_password": sip_auth_password,
                "inbound_agent_id": inbound_agent_id,
                "outbound_agent_id": outbound_agent_id,
                "inbound_agent_version": inbound_agent_version,
                "outbound_agent_version": outbound_agent_version,
                "nickname": nickname,
                "inbound_webhook_url": inbound_webhook_url,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    ImportNumberTelephonyResponse,
                    parse_obj_as(
                        type_=ImportNumberTelephonyResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 409:
                raise ConflictError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def list_numbers(
        self, *, limit: typing.Optional[int] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Retrieve a list of all phone numbers configured for SIP trunking within your organization, including their bound agents and current authentication state.

        Parameters
        ----------
        limit : typing.Optional[int]
            Number of phone numbers to return per page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from ortavox import OrtaVox

        client = OrtaVox(
            api_key="YOUR_API_KEY",
            token="YOUR_TOKEN",
        )
        client.telephony.list_numbers()
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/telephony/numbers",
            method="GET",
            params={
                "limit": limit,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def get_number(self, phone_number: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Retrieve details for a specific phone number

        Parameters
        ----------
        phone_number : str
            Phone number in E.164 format

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from ortavox import OrtaVox

        client = OrtaVox(
            api_key="YOUR_API_KEY",
            token="YOUR_TOKEN",
        )
        client.telephony.get_number(
            phone_number="+14157774444",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/telephony/numbers/{jsonable_encoder(phone_number)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def delete_number(self, phone_number: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Remove a phone number from the system

        Parameters
        ----------
        phone_number : str
            Phone number in E.164 format

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from ortavox import OrtaVox

        client = OrtaVox(
            api_key="YOUR_API_KEY",
            token="YOUR_TOKEN",
        )
        client.telephony.delete_number(
            phone_number="+14157774444",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/telephony/numbers/{jsonable_encoder(phone_number)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def update_number(
        self,
        phone_number: str,
        *,
        inbound_agent_id: typing.Optional[str] = OMIT,
        outbound_agent_id: typing.Optional[str] = OMIT,
        inbound_agent_version: typing.Optional[int] = OMIT,
        outbound_agent_version: typing.Optional[int] = OMIT,
        nickname: typing.Optional[str] = OMIT,
        inbound_webhook_url: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Update agent bindings and configuration for a phone number

        Parameters
        ----------
        phone_number : str
            Phone number in E.164 format

        inbound_agent_id : typing.Optional[str]

        outbound_agent_id : typing.Optional[str]

        inbound_agent_version : typing.Optional[int]

        outbound_agent_version : typing.Optional[int]

        nickname : typing.Optional[str]

        inbound_webhook_url : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from ortavox import OrtaVox

        client = OrtaVox(
            api_key="YOUR_API_KEY",
            token="YOUR_TOKEN",
        )
        client.telephony.update_number(
            phone_number="+14157774444",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/telephony/numbers/{jsonable_encoder(phone_number)}",
            method="PATCH",
            json={
                "inbound_agent_id": inbound_agent_id,
                "outbound_agent_id": outbound_agent_id,
                "inbound_agent_version": inbound_agent_version,
                "outbound_agent_version": outbound_agent_version,
                "nickname": nickname,
                "inbound_webhook_url": inbound_webhook_url,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncTelephonyClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def import_number(
        self,
        *,
        phone_number: str,
        termination_uri: str,
        direction: typing.Optional[ImportNumberTelephonyRequestDirection] = OMIT,
        sip_auth_username: typing.Optional[str] = OMIT,
        sip_auth_password: typing.Optional[str] = OMIT,
        inbound_agent_id: typing.Optional[str] = OMIT,
        outbound_agent_id: typing.Optional[str] = OMIT,
        inbound_agent_version: typing.Optional[int] = OMIT,
        outbound_agent_version: typing.Optional[int] = OMIT,
        nickname: typing.Optional[str] = OMIT,
        inbound_webhook_url: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ImportNumberTelephonyResponse:
        """
        Import a phone number from custom telephony and bind agents

        Parameters
        ----------
        phone_number : str
            E.164 format phone number

        termination_uri : str
            SIP trunk termination URI

        direction : typing.Optional[ImportNumberTelephonyRequestDirection]
            Which direction(s) to configure - inbound only, outbound only, or both. Defaults to both if not specified.

        sip_auth_username : typing.Optional[str]
            SIP authentication username (required)

        sip_auth_password : typing.Optional[str]
            SIP authentication password (required)

        inbound_agent_id : typing.Optional[str]
            Agent ID for inbound calls

        outbound_agent_id : typing.Optional[str]
            Agent ID for outbound calls

        inbound_agent_version : typing.Optional[int]
            Inbound agent version

        outbound_agent_version : typing.Optional[int]
            Outbound agent version

        nickname : typing.Optional[str]
            Friendly name for the phone number

        inbound_webhook_url : typing.Optional[str]
            Webhook URL for inbound call events

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ImportNumberTelephonyResponse
            Phone number imported successfully

        Examples
        --------
        import asyncio

        from ortavox import AsyncOrtaVox

        client = AsyncOrtaVox(
            api_key="YOUR_API_KEY",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.telephony.import_number(
                phone_number="+14157774444",
                termination_uri="sip.uk.didlogic.net",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/telephony/import",
            method="POST",
            json={
                "phone_number": phone_number,
                "termination_uri": termination_uri,
                "direction": direction,
                "sip_auth_username": sip_auth_username,
                "sip_auth_password": sip_auth_password,
                "inbound_agent_id": inbound_agent_id,
                "outbound_agent_id": outbound_agent_id,
                "inbound_agent_version": inbound_agent_version,
                "outbound_agent_version": outbound_agent_version,
                "nickname": nickname,
                "inbound_webhook_url": inbound_webhook_url,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    ImportNumberTelephonyResponse,
                    parse_obj_as(
                        type_=ImportNumberTelephonyResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 409:
                raise ConflictError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def list_numbers(
        self, *, limit: typing.Optional[int] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Retrieve a list of all phone numbers configured for SIP trunking within your organization, including their bound agents and current authentication state.

        Parameters
        ----------
        limit : typing.Optional[int]
            Number of phone numbers to return per page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from ortavox import AsyncOrtaVox

        client = AsyncOrtaVox(
            api_key="YOUR_API_KEY",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.telephony.list_numbers()


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/telephony/numbers",
            method="GET",
            params={
                "limit": limit,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def get_number(self, phone_number: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Retrieve details for a specific phone number

        Parameters
        ----------
        phone_number : str
            Phone number in E.164 format

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from ortavox import AsyncOrtaVox

        client = AsyncOrtaVox(
            api_key="YOUR_API_KEY",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.telephony.get_number(
                phone_number="+14157774444",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/telephony/numbers/{jsonable_encoder(phone_number)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def delete_number(
        self, phone_number: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Remove a phone number from the system

        Parameters
        ----------
        phone_number : str
            Phone number in E.164 format

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from ortavox import AsyncOrtaVox

        client = AsyncOrtaVox(
            api_key="YOUR_API_KEY",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.telephony.delete_number(
                phone_number="+14157774444",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/telephony/numbers/{jsonable_encoder(phone_number)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def update_number(
        self,
        phone_number: str,
        *,
        inbound_agent_id: typing.Optional[str] = OMIT,
        outbound_agent_id: typing.Optional[str] = OMIT,
        inbound_agent_version: typing.Optional[int] = OMIT,
        outbound_agent_version: typing.Optional[int] = OMIT,
        nickname: typing.Optional[str] = OMIT,
        inbound_webhook_url: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Update agent bindings and configuration for a phone number

        Parameters
        ----------
        phone_number : str
            Phone number in E.164 format

        inbound_agent_id : typing.Optional[str]

        outbound_agent_id : typing.Optional[str]

        inbound_agent_version : typing.Optional[int]

        outbound_agent_version : typing.Optional[int]

        nickname : typing.Optional[str]

        inbound_webhook_url : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from ortavox import AsyncOrtaVox

        client = AsyncOrtaVox(
            api_key="YOUR_API_KEY",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.telephony.update_number(
                phone_number="+14157774444",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/telephony/numbers/{jsonable_encoder(phone_number)}",
            method="PATCH",
            json={
                "inbound_agent_id": inbound_agent_id,
                "outbound_agent_id": outbound_agent_id,
                "inbound_agent_version": inbound_agent_version,
                "outbound_agent_version": outbound_agent_version,
                "nickname": nickname,
                "inbound_webhook_url": inbound_webhook_url,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
