# This file was auto-generated by Fern from our API Definition.

import typing
from ..core.client_wrapper import SyncClientWrapper
from .types.list_tools_request_type import ListToolsRequestType
from ..core.request_options import RequestOptions
from .types.list_tools_response import ListToolsResponse
from ..core.pydantic_utilities import parse_obj_as
from json.decoder import JSONDecodeError
from ..core.api_error import ApiError
from .types.create_tool_type import CreateToolType
from .types.create_tool_method import CreateToolMethod
from .types.create_tool_parameters import CreateToolParameters
from ..types.tool_response import ToolResponse
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.bad_request_error import BadRequestError
from ..core.jsonable_encoder import jsonable_encoder
from ..errors.not_found_error import NotFoundError
from .types.update_tool_method import UpdateToolMethod
from ..core.client_wrapper import AsyncClientWrapper

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ToolsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(
        self,
        *,
        type: typing.Optional[ListToolsRequestType] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListToolsResponse:
        """
        List all tools (end_call and api) for the organization

        Parameters
        ----------
        type : typing.Optional[ListToolsRequestType]
            Filter by tool type

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListToolsResponse
            List of tools

        Examples
        --------
        from ortavox import OrtaVox

        client = OrtaVox(
            api_key="YOUR_API_KEY",
            token="YOUR_TOKEN",
        )
        client.tools.list()
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/tools",
            method="GET",
            params={
                "type": type,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    ListToolsResponse,
                    parse_obj_as(
                        type_=ListToolsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def create(
        self,
        *,
        name: str,
        type: CreateToolType,
        description: typing.Optional[str] = OMIT,
        url: typing.Optional[str] = OMIT,
        method: typing.Optional[CreateToolMethod] = OMIT,
        headers: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        parameters: typing.Optional[CreateToolParameters] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ToolResponse:
        """
        Create an end_call or API tool for agents to use

        Parameters
        ----------
        name : str
            Tool name

        type : CreateToolType
            Tool type

        description : typing.Optional[str]
            Tool description (optional, auto-generated if not provided)

        url : typing.Optional[str]
            API endpoint URL (required for api type)

        method : typing.Optional[CreateToolMethod]
            HTTP method (required for api type)

        headers : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]
            HTTP headers for api type

        parameters : typing.Optional[CreateToolParameters]
            JSON Schema for tool parameters

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ToolResponse
            Tool created successfully

        Examples
        --------
        from ortavox import OrtaVox

        client = OrtaVox(
            api_key="YOUR_API_KEY",
            token="YOUR_TOKEN",
        )
        client.tools.create(
            name="API request",
            type="end_call",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/tools",
            method="POST",
            json={
                "name": name,
                "type": type,
                "description": description,
                "url": url,
                "method": method,
                "headers": headers,
                "parameters": convert_and_respect_annotation_metadata(
                    object_=parameters, annotation=CreateToolParameters, direction="write"
                ),
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    ToolResponse,
                    parse_obj_as(
                        type_=ToolResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> ToolResponse:
        """
        Get details of a specific tool by ID

        Parameters
        ----------
        id : str
            Tool ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ToolResponse
            Tool details

        Examples
        --------
        from ortavox import OrtaVox

        client = OrtaVox(
            api_key="YOUR_API_KEY",
            token="YOUR_TOKEN",
        )
        client.tools.get(
            id="id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/tools/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    ToolResponse,
                    parse_obj_as(
                        type_=ToolResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def update(
        self,
        id: str,
        *,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        goodbye_message: typing.Optional[str] = OMIT,
        url: typing.Optional[str] = OMIT,
        method: typing.Optional[UpdateToolMethod] = OMIT,
        headers: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        parameters: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ToolResponse:
        """
        Update a custom tool (cannot update default tools)

        Parameters
        ----------
        id : str
            Tool ID

        name : typing.Optional[str]

        description : typing.Optional[str]

        goodbye_message : typing.Optional[str]

        url : typing.Optional[str]

        method : typing.Optional[UpdateToolMethod]

        headers : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        parameters : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ToolResponse
            Tool updated successfully

        Examples
        --------
        from ortavox import OrtaVox

        client = OrtaVox(
            api_key="YOUR_API_KEY",
            token="YOUR_TOKEN",
        )
        client.tools.update(
            id="id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/tools/{jsonable_encoder(id)}",
            method="PUT",
            json={
                "name": name,
                "description": description,
                "goodbye_message": goodbye_message,
                "url": url,
                "method": method,
                "headers": headers,
                "parameters": parameters,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    ToolResponse,
                    parse_obj_as(
                        type_=ToolResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Delete a custom tool (cannot delete default tools)

        Parameters
        ----------
        id : str
            Tool ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from ortavox import OrtaVox

        client = OrtaVox(
            api_key="YOUR_API_KEY",
            token="YOUR_TOKEN",
        )
        client.tools.delete(
            id="id",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v1/tools/{jsonable_encoder(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncToolsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self,
        *,
        type: typing.Optional[ListToolsRequestType] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListToolsResponse:
        """
        List all tools (end_call and api) for the organization

        Parameters
        ----------
        type : typing.Optional[ListToolsRequestType]
            Filter by tool type

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListToolsResponse
            List of tools

        Examples
        --------
        import asyncio

        from ortavox import AsyncOrtaVox

        client = AsyncOrtaVox(
            api_key="YOUR_API_KEY",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.tools.list()


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/tools",
            method="GET",
            params={
                "type": type,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    ListToolsResponse,
                    parse_obj_as(
                        type_=ListToolsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def create(
        self,
        *,
        name: str,
        type: CreateToolType,
        description: typing.Optional[str] = OMIT,
        url: typing.Optional[str] = OMIT,
        method: typing.Optional[CreateToolMethod] = OMIT,
        headers: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        parameters: typing.Optional[CreateToolParameters] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ToolResponse:
        """
        Create an end_call or API tool for agents to use

        Parameters
        ----------
        name : str
            Tool name

        type : CreateToolType
            Tool type

        description : typing.Optional[str]
            Tool description (optional, auto-generated if not provided)

        url : typing.Optional[str]
            API endpoint URL (required for api type)

        method : typing.Optional[CreateToolMethod]
            HTTP method (required for api type)

        headers : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]
            HTTP headers for api type

        parameters : typing.Optional[CreateToolParameters]
            JSON Schema for tool parameters

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ToolResponse
            Tool created successfully

        Examples
        --------
        import asyncio

        from ortavox import AsyncOrtaVox

        client = AsyncOrtaVox(
            api_key="YOUR_API_KEY",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.tools.create(
                name="API request",
                type="end_call",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/tools",
            method="POST",
            json={
                "name": name,
                "type": type,
                "description": description,
                "url": url,
                "method": method,
                "headers": headers,
                "parameters": convert_and_respect_annotation_metadata(
                    object_=parameters, annotation=CreateToolParameters, direction="write"
                ),
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    ToolResponse,
                    parse_obj_as(
                        type_=ToolResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> ToolResponse:
        """
        Get details of a specific tool by ID

        Parameters
        ----------
        id : str
            Tool ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ToolResponse
            Tool details

        Examples
        --------
        import asyncio

        from ortavox import AsyncOrtaVox

        client = AsyncOrtaVox(
            api_key="YOUR_API_KEY",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.tools.get(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/tools/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    ToolResponse,
                    parse_obj_as(
                        type_=ToolResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def update(
        self,
        id: str,
        *,
        name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        goodbye_message: typing.Optional[str] = OMIT,
        url: typing.Optional[str] = OMIT,
        method: typing.Optional[UpdateToolMethod] = OMIT,
        headers: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        parameters: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ToolResponse:
        """
        Update a custom tool (cannot update default tools)

        Parameters
        ----------
        id : str
            Tool ID

        name : typing.Optional[str]

        description : typing.Optional[str]

        goodbye_message : typing.Optional[str]

        url : typing.Optional[str]

        method : typing.Optional[UpdateToolMethod]

        headers : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        parameters : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ToolResponse
            Tool updated successfully

        Examples
        --------
        import asyncio

        from ortavox import AsyncOrtaVox

        client = AsyncOrtaVox(
            api_key="YOUR_API_KEY",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.tools.update(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/tools/{jsonable_encoder(id)}",
            method="PUT",
            json={
                "name": name,
                "description": description,
                "goodbye_message": goodbye_message,
                "url": url,
                "method": method,
                "headers": headers,
                "parameters": parameters,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    ToolResponse,
                    parse_obj_as(
                        type_=ToolResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Delete a custom tool (cannot delete default tools)

        Parameters
        ----------
        id : str
            Tool ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from ortavox import AsyncOrtaVox

        client = AsyncOrtaVox(
            api_key="YOUR_API_KEY",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.tools.delete(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v1/tools/{jsonable_encoder(id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
