# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class AgentResponseDataConfiguration(UniversalBaseModel):
    model: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = None
    voice: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = None
    transcriber: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = None
    start_message: typing.Optional[str] = None
    start_message_mode: typing.Optional[str] = None
    max_call_duration: typing.Optional[float] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
