# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from .api_key_response_data_tag import ApiKeyResponseDataTag
import typing_extensions
import datetime as dt
from ..core.serialization import FieldMetadata
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class ApiKeyResponseData(UniversalBaseModel):
    id: typing.Optional[str] = None
    name: typing.Optional[str] = None
    key: typing.Optional[str] = pydantic.Field(default=None)
    """
    Full key (only shown once on creation)
    """

    tag: typing.Optional[ApiKeyResponseDataTag] = None
    restrictions: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = None
    permissions: typing.Optional[typing.List[str]] = None
    created_at: typing_extensions.Annotated[typing.Optional[dt.datetime], FieldMetadata(alias="createdAt")] = None
    updated_at: typing_extensions.Annotated[typing.Optional[dt.datetime], FieldMetadata(alias="updatedAt")] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
