# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
from .create_agent_transcriber import CreateAgentTranscriber
from .create_agent_model import CreateAgentModel
from .create_agent_voice import CreateAgentVoice
import typing
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class CreateAgent(UniversalBaseModel):
    name: str = pydantic.Field()
    """
    Agent name
    """

    transcriber: CreateAgentTranscriber
    model: CreateAgentModel
    voice: CreateAgentVoice
    max_call_duration: typing.Optional[float] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
