# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing_extensions
import typing
from ..core.serialization import FieldMetadata
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class CreateApiKeyRestrictions(UniversalBaseModel):
    allowed_agents_ids: typing_extensions.Annotated[
        typing.Optional[typing.List[str]], FieldMetadata(alias="allowedAgentsIds")
    ] = pydantic.Field(default=None)
    """
    List of agent IDs this key can access
    """

    allowed_origins: typing_extensions.Annotated[
        typing.Optional[typing.List[str]], FieldMetadata(alias="allowedOrigins")
    ] = pydantic.Field(default=None)
    """
    List of allowed origins (for public keys)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
