# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing
from .create_api_key_tag import CreateApiKeyTag
from .create_api_key_restrictions import CreateApiKeyRestrictions
import typing_extensions
import datetime as dt
from ..core.serialization import FieldMetadata
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class CreateApiKey(UniversalBaseModel):
    name: str = pydantic.Field()
    """
    API key name
    """

    tag: typing.Optional[CreateApiKeyTag] = pydantic.Field(default=None)
    """
    Key type: private (sk_live_) or public (pk_live_)
    """

    restrictions: typing.Optional[CreateApiKeyRestrictions] = None
    permissions: typing.Optional[typing.List[str]] = None
    expires_at: typing_extensions.Annotated[typing.Optional[dt.datetime], FieldMetadata(alias="expiresAt")] = (
        pydantic.Field(default=None)
    )
    """
    Optional expiration date
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
