# This file was auto-generated by Fern from our API Definition.

import typing

CreateAgentModelProvider = typing.Union[
    typing.Literal["openai", "anthropic", "google", "groq", "deep-seek"], typing.Any
]
