# This file was auto-generated by Fern from our API Definition.

import typing

CreateAgentTranscriberProvider = typing.Union[
    typing.Literal["deepgram", "openai", "assemblyai", "google", "speechmatics", "azure"], typing.Any
]
