# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class ImportPhoneNumber(UniversalBaseModel):
    phone_number: str = pydantic.Field()
    """
    Phone number in E.164 format
    """

    termination_uri: str = pydantic.Field()
    """
    SIP trunk termination URI
    """

    sip_trunk_auth_username: typing.Optional[str] = pydantic.Field(default=None)
    """
    SIP trunk authentication username
    """

    sip_trunk_auth_password: typing.Optional[str] = pydantic.Field(default=None)
    """
    SIP trunk authentication password
    """

    inbound_agent_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Agent ID for inbound calls
    """

    outbound_agent_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Agent ID for outbound calls
    """

    inbound_agent_version: typing.Optional[int] = pydantic.Field(default=None)
    """
    Inbound agent version
    """

    outbound_agent_version: typing.Optional[int] = pydantic.Field(default=None)
    """
    Outbound agent version
    """

    nickname: typing.Optional[str] = pydantic.Field(default=None)
    """
    Friendly name for the phone number
    """

    inbound_webhook_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    Webhook URL for inbound call events
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
