# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class PhoneNumberResponse(UniversalBaseModel):
    phone_number: typing.Optional[str] = None
    phone_number_type: typing.Optional[str] = None
    phone_number_pretty: typing.Optional[str] = None
    inbound_agent_id: typing.Optional[str] = None
    outbound_agent_id: typing.Optional[str] = None
    inbound_agent_version: typing.Optional[int] = None
    outbound_agent_version: typing.Optional[int] = None
    area_code: typing.Optional[int] = None
    nickname: typing.Optional[str] = None
    inbound_webhook_url: typing.Optional[str] = None
    last_modification_timestamp: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
