# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .tool_response_data_tool_type import ToolResponseDataToolType
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class ToolResponseDataTool(UniversalBaseModel):
    type: typing.Optional[ToolResponseDataToolType] = None
    name: typing.Optional[str] = None
    description: typing.Optional[str] = None
    parameters: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = None
    url: typing.Optional[str] = None
    method: typing.Optional[str] = None
    headers: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = None
    goodbye_message: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
