# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .tool_response_data_type import ToolResponseDataType
import typing_extensions
import datetime as dt
from ..core.serialization import FieldMetadata
from .tool_response_data_tool import ToolResponseDataTool
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class ToolResponseData(UniversalBaseModel):
    id: typing.Optional[str] = None
    type: typing.Optional[ToolResponseDataType] = None
    created_at: typing_extensions.Annotated[typing.Optional[dt.datetime], FieldMetadata(alias="createdAt")] = None
    updated_at: typing_extensions.Annotated[typing.Optional[dt.datetime], FieldMetadata(alias="updatedAt")] = None
    tool: typing.Optional[ToolResponseDataTool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
